import fs from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

// Generated by `pnpm run i18n:item-names`; these guard the generator, not the
// translations, so a regression there fails here instead of in the app.
const NAMES_DIR = path.resolve(__dirname, "../../src/data/itemNames");

// A generator bug can miss thousands of keys at once, and vitest prints the
// whole diff, so every failure list is trimmed before it reaches the matcher.
const MAX_REPORTED = 20;

const trim = (offenders: string[]): string[] =>
  offenders.length > MAX_REPORTED
    ? [...offenders.slice(0, MAX_REPORTED), `... ${offenders.length - MAX_REPORTED} more`]
    : offenders;

const locales = fs
  .readdirSync(NAMES_DIR)
  .filter((file) => file.endsWith(".json"))
  .map((file) => path.basename(file, ".json"))
  .sort();

const names = (locale: string): Record<string, string> =>
  JSON.parse(fs.readFileSync(path.join(NAMES_DIR, `${locale}.json`), "utf8"));

const english = names("en");

describe("generated item names", () => {
  it("ships a parseable, non-empty map for every locale", () => {
    expect(locales).toContain("en");
    expect(locales).toContain("de");

    const broken: string[] = [];
    for (const locale of locales) {
      const map = names(locale);
      if (Object.keys(map).length === 0) broken.push(`${locale}: empty`);
      const nonString = Object.entries(map).find(([, value]) => typeof value !== "string");
      if (nonString) broken.push(`${locale}: ${nonString[0]} is not a string`);
    }

    expect(broken).toEqual([]);
  });

  it("keys every entry by its Lotus language path", () => {
    const stray: string[] = [];
    for (const locale of locales) {
      for (const key of Object.keys(names(locale))) {
        if (!key.startsWith("/Lotus/Language/")) stray.push(`${locale}: ${key}`);
      }
    }

    expect(trim(stray)).toEqual([]);
  });

  it("names only keys English defines", () => {
    // English is the harvest of every key, so anything extra means a locale
    // file went stale against a newer export.
    const unknown: string[] = [];
    for (const locale of locales) {
      if (locale === "en") continue;
      for (const key of Object.keys(names(locale))) {
        if (!(key in english)) unknown.push(`${locale}: ${key}`);
      }
    }

    expect(trim(unknown)).toEqual([]);
  });

  it("drops every translation identical to the English one", () => {
    // The app falls back to English, so a copy of it is weight the generator
    // is supposed to skip.
    const redundant: string[] = [];
    for (const locale of locales) {
      if (locale === "en") continue;
      for (const [key, value] of Object.entries(names(locale))) {
        if (value === english[key]) redundant.push(`${locale}: ${key}`);
      }
    }

    expect(trim(redundant)).toEqual([]);
  });

  it("keeps German covering most of what English names", () => {
    const coverage = Object.keys(names("de")).length / Object.keys(english).length;

    expect(coverage).toBeGreaterThanOrEqual(0.6);
  });
});
