// Generated by scripts/codex-scans/build-codex-scan-data.mjs - do not edit.
// Source: wiki.warframe.com Module:Enemies/data/* (CC BY-SA).

export const CODEX_SCAN_REQUIREMENTS: Record<string, { name: string; scans: number }> = {
  "/Lotus/Language/Railjack/CorpusFighterPlutoLaserName": { name: "Vorac Harpi", scans: 5 },
  "/Lotus/Powersuits/Brawler/SummonHostileAgent": { name: "Tomb Guardian", scans: 1 },
  "/Lotus/Types/Enemies/Acolytes/AreaCasterAcolyteAgent": { name: "Misery", scans: 3 },
  "/Lotus/Types/Enemies/Acolytes/ControlAcolyteAgent": { name: "Torment", scans: 3 },
  "/Lotus/Types/Enemies/Acolytes/DuellistAcolyteAgent": { name: "Violence", scans: 3 },
  "/Lotus/Types/Enemies/Acolytes/HeavyAcolyteAgent": { name: "Malice", scans: 3 },
  "/Lotus/Types/Enemies/Acolytes/RogueAcolyteAgent": { name: "Mania", scans: 3 },
  "/Lotus/Types/Enemies/Acolytes/StrikerAcolyteAgent": { name: "Angst", scans: 3 },
  "/Lotus/Types/Enemies/CaptureTargets/CaptureTargetCorpusNullifier": {
    name: "Nullifier Target",
    scans: 20,
  },
  "/Lotus/Types/Enemies/CaptureTargets/CaptureTargetGhoulAgent": { name: "Ghoul Target", scans: 3 },
  "/Lotus/Types/Enemies/CaptureTargets/CaptureTargetGrineerGhoulShip": {
    name: "Instigator Ghoul",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/AladVPet/AladVPet": { name: "Zanuka", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/AladVPet/ZanukaHunterAgent": { name: "Zanuka Hunter", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamCarrusAgent": { name: "Amalgam Kucumatz", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamCarrusPilotAgent": {
    name: "Amalgam Machinist",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamCarrusPilotBossAgent": {
    name: "Demolyst Machinist",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamCorpusOverrideAgent": {
    name: "Amalgam Alkonost",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamCorpusSniperAgent": {
    name: "Amalgam Heqet",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamCorpusSniperBossAgent": {
    name: "Demolyst Heqet",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamMoaAgent": { name: "Amalgam MOA", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamMoaBossAgent": { name: "Demolyst MOA", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamMoaSatyrAgent": { name: "Amalgam Satyr", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamMoaSatyrBossAgent": {
    name: "Demolyst Satyr",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamOspreyAgent": { name: "Amalgam Osprey", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamOspreyBossAgent": {
    name: "Demolyst Osprey",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/AmalgamPilotGhostBossAgent": { name: "Demolyst", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Amalgams/CorpusCarrusPilotAgent": { name: "Machinist", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Amalgams/Prototypes/AmalgamPrototypeCarrusAgent": {
    name: "Amalgam Arca Kucumatz",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/Prototypes/AmalgamPrototypeCarrusPilotAgent": {
    name: "Amalgam Cinder Machinist",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/Prototypes/AmalgamPrototypeMeleeAgent": {
    name: "Amalgam Arca Heqet",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/Prototypes/AmalgamPrototypeMoaAgent": {
    name: "Amalgam Phase MOA",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Amalgams/Prototypes/AmalgamPrototypeSatyrAgent": {
    name: "Amalgam Swarm Satyr",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Aristocrats/AristocratManagerAgent": {
    name: "Treasurer",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/Aristocrats/MiniMoaAgent": { name: "Minima MOA", scans: 20 },
  "/Lotus/Types/Enemies/Corpus/BipedRobot/AIWeek/LaserCannonBipedAgent": { name: "MOA", scans: 20 },
  "/Lotus/Types/Enemies/Corpus/BipedRobot/AIWeek/LaserDiscBipedAgent": {
    name: "Anti MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/BipedRobot/AIWeek/RailgunBipedAgent": {
    name: "Railgun MOA",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/BipedRobot/AIWeek/RiotBipedControlAgent": {
    name: "Drover Bursa",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/BipedRobot/AIWeek/RiotBipedDispersionAgent": {
    name: "Isolator Bursa",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/BipedRobot/AIWeek/RiotBipedPreventionAgent": {
    name: "Denial Bursa",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/BipedRobot/AIWeek/ShockwaveBipedAgent": {
    name: "Shockwave MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/BipedRobot/AIWeek/SuperMoaBipedAgent": {
    name: "Fusion MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipCombaDetectorAgent": {
    name: "Juno Fog Comba",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipCombaLaserAgent": {
    name: "Juno Sap Comba",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipCombaShieldAgent": {
    name: "Juno Nul Comba",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipCombaTeslaAgent": {
    name: "Juno Slo Comba",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipCrewmanAgent": {
    name: "Juno Crewman",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipCrewmanEliteAgent": {
    name: "Juno Elite Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipCrewmanNullifierAgent": {
    name: "Juno Nullifier Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipCrewmanSniperAgent": {
    name: "Juno Sniper Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipCrewmanTechAgent": {
    name: "Juno Tech",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipMachinistHammerAgent": {
    name: "Juno Malleus Machinist",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipMoaDeraAgent": {
    name: "Juno Dera MOA",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipMoaDiscAgent": {
    name: "Juno Disc MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipMoaDualCannonAgent": {
    name: "Juno Geminex MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipMoaGlaxionAgent": {
    name: "Juno Glaxion MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipOspreyMineAgent": {
    name: "Juno Jactus Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipOspreyOxiumAgent": {
    name: "Juno Oxium Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/CorpusShipRemastered/ShipOspreyShieldAgent": {
    name: "Juno Shield Osprey",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/Disruption/DisruptionCarrusPilotAgent": {
    name: "Demolisher Machinist",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Disruption/DisruptionHyenaAgent": {
    name: "Demolisher Hyena",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Disruption/DisruptionLaserDiscBipedAgent": {
    name: "Demolisher Anti MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Disruption/DisruptionRiotMoaAgent": {
    name: "Demolisher Bursa",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Drones/AIWeek/DiscDroneAgent": { name: "Sapping Osprey", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Drones/AIWeek/LeechDroneAgent": { name: "Leech Osprey", scans: 10 },
  "/Lotus/Types/Enemies/Corpus/Drones/AIWeek/MineDroneAgent": { name: "Mine Osprey", scans: 10 },
  "/Lotus/Types/Enemies/Corpus/Drones/AIWeek/ShieldDroneAgent": {
    name: "Shield Osprey",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/Drones/AIWeek/SuicideDroneAgent": { name: "Oxium Osprey", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Drones/AIWeek/VacuumDroneAgent": {
    name: "Scavenger Drone",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Drones/DroneAttackAgent": { name: "Attack Drone", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Drones/Vip/RaptorPack": { name: "The Raptor", scans: 10 },
  "/Lotus/Types/Enemies/Corpus/Drones/Vip/RaptorTwoCarrierAgent": { name: "Raptor Mt", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Drones/Vip/RaptorTwoLaserAgent": { name: "Raptor Rv", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Drones/Vip/RaptorTwoMortarAgent": { name: "Raptor Ns", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Drones/Vip/RaptorTwoSwarmDroneAgent": {
    name: "Nemes Rt",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Dropship/CorpusDropshipAgent": {
    name: "Condor Dropship",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Dropship/CorpusHunterShipAgent": {
    name: "Vapos Condor Dropship",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Dropship/CorpusHunterShipEliteAgent": {
    name: "Vapos Condor Elite Dropship",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Dropship/SpaceFighterLaserHunterShipAgent": {
    name: "Vapos Aquila",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Dropship/Venus/VenusDropshipAgent": {
    name: "Condor Dropship",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Dropship/Venus/VenusSmallDropshipAgent": {
    name: "Buzzard Dropship",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Gamemodes/Ascension/AscensionCannonMoaAgent": {
    name: "Juno Sapper MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Gamemodes/DeployableSpacemanWardenAgent": {
    name: "Corpus Warden",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Gamemodes/PurgatoryGhost": { name: "Specter Particles", scans: 20 },
  "/Lotus/Types/Enemies/Corpus/Gamemodes/PurgatoryWarrior": { name: "Errant Specter", scans: 30 },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasDeployableSpacemanAgent": {
    name: "Vapos Tech",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasDiscDroneAgent": {
    name: "Vapos Sapping Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasEliteSpacemanAgent": {
    name: "Vapos Elite Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasFlyingDeployableSpacemanAgent": {
    name: "Vapos Tech Ranger",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasFlyingEliteSpacemanAgent": {
    name: "Vapos Elite Ranger",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasFlyingNullifierSpacemanAgent": {
    name: "Vapos Nullifier Ranger",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasFlyingShotgunSpacemanAgent": {
    name: "Vapos Detron Ranger",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasFlyingSniperSpacemanAgent": {
    name: "Vapos Sniper Ranger",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasFlyingSpacemanAgent": { name: "Vapos Ranger", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasLaserCannonBipedAgent": { name: "Vapos MOA", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasLaserDiscBipedAgent": {
    name: "Vapos Anti MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasMeleeSpacemanAgent": {
    name: "Vapos Prod Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasNullifySpacemanAgent": {
    name: "Vapos Nullifier",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasRailgunBipedAgent": {
    name: "Vapos Railgun MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasRifleSpacemanAgent": { name: "Vapos Crewman", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasScientistAgent": { name: "Vapos Bioengineer", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasShieldDroneAgent": {
    name: "Vapos Shield Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasShockwaveBipedAgent": {
    name: "Vapos Shockwave MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasShotgunSpacemanAgent": {
    name: "Vapos Detron Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasSniperSpacemanAgent": {
    name: "Vapos Sniper Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasSuicideDroneAgent": {
    name: "Vapos Oxium Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/GasCity/GasSuperMoaBipedAgent": {
    name: "Vapos Fusion MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Narmer/Avatars/NarmerRifleSpacemanAvatar": {
    name: "Narmer Crewman",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/Narmer/NarmerGuardSpacemanAgent": {
    name: "Narmer Jailer",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Narmer/NarmerSpacemanCarrierAgent": {
    name: "Narmer Power Carrier",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Narmer/PNWNarmerDiscDroneAgent": {
    name: "Narmer Sapping Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Narmer/PNWNarmerShipMoaDeraAgent": {
    name: "Narmer Dera MOA",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/QuadRobot/MicroHyenaAgent": { name: "Ratel", scans: 20 },
  "/Lotus/Types/Enemies/Corpus/QuadRobot/MiniBoss/QuadRobotMiniBossAgent": {
    name: "Lynx",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/QuadRobot/MiniBoss/ShieldDroneMiniBossAgent": {
    name: "Lynx Osprey",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/QuadRobot/MiniBoss/TurretQuadMiniBossAgent": {
    name: "Lynx Turret",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/QuadRobot/QuadRobotAgentNEW": { name: "Jackal", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Railjack/BoardingMeleeSpacemanAgent": {
    name: "Taro Zerca",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/BoardingRifleSpacemanAgent": {
    name: "Taro Vambac",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/BoardingShotgunSpacemanAgent": {
    name: "Taro Numon",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CorpusRailjackFlyingSpacemanAgent": {
    name: "Taro Ranger Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpAdmiralFlyingAgent": { name: "Optio", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewCannonBipedAgent": { name: "Taro MOA", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewDiscBipedAgent": { name: "Taro Disc MOA", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewEliteAgent": {
    name: "Taro Elite Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewmanTechDeployableAgent": {
    name: "Taro Tech",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewNullifierAgent": {
    name: "Taro Nullifier Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewRifleAgent": { name: "Taro Crewman", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewRJRailgunAgent": {
    name: "Taro Railgun MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewShieldDroneAgent": {
    name: "Taro Shield Osprey",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewshipCaptain": { name: "Taro Pilot", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpCrewShotgunAgent": {
    name: "Taro Detron Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpRailjackShockwaveBipedAgent": {
    name: "Taro Shockwave MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpSpecOpsMinigunAgent": { name: "Aurax Vertec", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpSpecOpsRiotBipedControlAgent": {
    name: "Tarask Bursa",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpSpecOpsShockerAgent": {
    name: "Aurax Actinic",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/CrpTechEngineerAgent": { name: "Taro Engineer", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceBoardingMeleeSpacemanAgent": {
    name: "Orm Zerca",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceBoardingRifleSpacemanAgent": {
    name: "Orm Vambac",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceBoardingShotgunSpacemanAgent": {
    name: "Orm Numon",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCorpusRailjackFlyingSpacemanAgent": {
    name: "Orm Ranger Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewCannonBipedAgent": {
    name: "Orm MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewDiscBipedAgent": {
    name: "Orm Disc MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewEliteAgent": {
    name: "Orm Elite Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewmanTechDeployableAgent": {
    name: "Orm Tech",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewMeleeAgent": {
    name: "Orm Stropha Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewNullifierAgent": {
    name: "Orm Nullifier Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewRifleAgent": {
    name: "Orm Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewRJRailgunAgent": {
    name: "Orm Railgun MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewShieldDroneAgent": {
    name: "Orm Shield Osprey",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewshipCaptain": {
    name: "Orm Pilot",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpCrewShotgunAgent": {
    name: "Orm Detron Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpRailjackShockwaveBipedAgent": {
    name: "Orm Shockwave MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/DeepSpace/DeepSpaceCrpTechEngineerAgent": {
    name: "Orm Engineer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneBoardingMeleeSpacemanAgent": {
    name: "Axio Zerca",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneBoardingRifleSpacemanAgent": {
    name: "Axio Vambac",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneBoardingShotgunSpacemanAgent": {
    name: "Axio Numon",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCorpusRailjackFlyingSpacemanAgent": {
    name: "Axio Ranger Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewCannonBipedAgent": {
    name: "Axio MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewDiscBipedAgent": {
    name: "Axio Disc MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewEliteAgent": {
    name: "Axio Elite Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewmanTechDeployableAgent": {
    name: "Axio Tech",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewMeleeAgent": {
    name: "Axio Stropha Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewNullifierAgent": {
    name: "Axio Nullifier Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewRifleAgent": {
    name: "Axio Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewRJRailgunAgent": {
    name: "Axio Railgun MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewShieldDroneAgent": {
    name: "Axio Shield Osprey",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewshipCaptain": {
    name: "Axio Pilot",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpCrewShotgunAgent": {
    name: "Axio Detron Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpRailjackShockwaveBipedAgent": {
    name: "Axio Shockwave MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Neptune/NeptuneCrpTechEngineerAgent": {
    name: "Axio Engineer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/OverrideJammingDroneAgent": {
    name: "Taro Secura Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoBoardingMeleeSpacemanAgent": {
    name: "Vorac Zerca",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoBoardingRifleSpacemanAgent": {
    name: "Vorac Vambac",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoBoardingShotgunSpacemanAgent": {
    name: "Vorac Numon",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCorpusRailjackFlyingSpacemanAgent": {
    name: "Vorac Ranger Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewCannonBipedAgent": {
    name: "Vorac MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewDiscBipedAgent": {
    name: "Vorac Disc MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewEliteAgent": {
    name: "Vorac Elite Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewmanTechDeployableAgent": {
    name: "Vorac Tech",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewMeleeAgent": {
    name: "Vorac Stropha Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewNullifierAgent": {
    name: "Vorac Nullifier Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewRifleAgent": {
    name: "Vorac Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewRJRailgunAgent": {
    name: "Vorac Railgun MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewShieldDroneAgent": {
    name: "Vorac Shield Osprey",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewshipCaptain": {
    name: "Vorac Pilot",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpCrewShotgunAgent": {
    name: "Vorac Detron Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpRailjackShockwaveBipedAgent": {
    name: "Vorac Shockwave MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/Pluto/PlutoCrpTechEngineerAgent": {
    name: "Vorac Engineer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/SpecOpsArachnoidAgent": {
    name: "Aurax Atloc Raknoid",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/SpecOpsFireMoaAgent": {
    name: "Aurax Culveri MOA",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/SpecOpsIceMoaAgent": {
    name: "Aurax Polaris MOA",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Railjack/SpecOpsStaffAgent": { name: "Aurax Baculus", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Spaceman/AIWeek/CarrierSpacemanAgent": {
    name: "Corpus Power Carrier",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/AIWeek/DeployableSpacemanAgent": {
    name: "Corpus Tech",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/AIWeek/MeleeSpacemanAgent": {
    name: "Prod Crewman",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/AIWeek/NullifySpacemanAgent": {
    name: "Nullifier Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/AIWeek/RifleSpacemanAgent": { name: "Crewman", scans: 20 },
  "/Lotus/Types/Enemies/Corpus/Spaceman/AIWeek/ShotgunSpacemanAgent": {
    name: "Detron Crewman",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/AIWeek/SniperSpacemanAgent": {
    name: "Sniper Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/EliteSpacemanAgent": { name: "Elite Crewman", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Spaceman/ModularSpacemanAgentSkatingDetector": {
    name: "Fog Scrambus",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/ModularSpacemanAgentSkatingLaser": {
    name: "Sap Scrambus",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/ModularSpacemanAgentSkatingShield": {
    name: "Nul Scrambus",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/ModularSpacemanAgentSkatingTesla": {
    name: "Slo Scrambus",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/ModularSpacemanAgentWalkingDetector": {
    name: "Fog Comba",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/ModularSpacemanAgentWalkingLaser": {
    name: "Sap Comba",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/ModularSpacemanAgentWalkingShield": {
    name: "Nul Comba",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/ModularSpacemanAgentWalkingTesla": {
    name: "Slo Comba",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Spaceman/Vip/SniperAgent": { name: "The Sergeant", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/SpecialEvents/ArmoredJackal/ArmoredJackalAgent": {
    name: "Razorback",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/SpecialEvents/ArtificerSuicideDroneAgent": {
    name: "Nemes",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/SpecialEvents/CorpusArtificer": { name: "Datalyst", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Turrets/AutoTurretHeavyAgent": { name: "Senta Turret", scans: 20 },
  "/Lotus/Types/Enemies/Corpus/Turrets/CartTurretLaserAgent": { name: "Senta Turret", scans: 20 },
  "/Lotus/Types/Enemies/Corpus/Turrets/SecurityCameraAgent": { name: "Security Camera", scans: 20 },
  "/Lotus/Types/Enemies/Corpus/Vehicle/WheelCarAgent": { name: "Coildrive", scans: 1 },
  "/Lotus/Types/Enemies/Corpus/Venus/Commanders/VenusCommanderAquaAgent": {
    name: "Armaments Director",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Commanders/VenusCommanderGreenAgent": {
    name: "Vivisect Director",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Commanders/VenusCommanderOrangeAgent": {
    name: "Sentient Research Director",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/Ambulas/VenusAmbulasAgent": {
    name: "Terra Ambulas",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/Hyenas/VenusHyenaAstroAgent": {
    name: "Icemire Hyena",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/Hyenas/VenusHyenaBurnerAgent": {
    name: "Rabbleback Hyena",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/Hyenas/VenusHyenaHotrodAgent": {
    name: "Gyre Hyena",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/Hyenas/VenusHyenaPacerAgent": {
    name: "Cinderthresh Hyena",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/QuadAgent": { name: "Terra Jackal", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusCombatSpacemanAgent": {
    name: "Terra Manker",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusFlyingEliteSpacemanAgent": {
    name: "Terra Elite Provisor",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusFlyingSpacemanAgent": {
    name: "Terra Provisor",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusGrenadierEliteSpacemanAgent": {
    name: "Terra Elite Overtaker",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusGrenadierSpacemanAgent": {
    name: "Terra Overtaker",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusGuardSpacemanAgent": {
    name: "Terra Jailer",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusHeavyDroneAgent": {
    name: "Terra Raptor SX",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusHeavyEliteDroneAgent": {
    name: "Terra Elite Raptor Sx",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusHeavyMeleeEliteSpacemanAgent": {
    name: "Terra Elite Trencher",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusHeavyMeleeSpacemanAgent": {
    name: "Terra Trencher",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusIcewaveBipedAgent": {
    name: "Terra Embattor MOA",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Heavies/VenusIcewaveEliteBipedAgent": {
    name: "Terra Elite Embattor MOA",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusAutoTurretAgent": { name: "Terra Auto Turret", scans: 1 },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusAutoTurretAgentRocket": {
    name: "Terra Rocket Turret",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusDefenseDroneAgent": {
    name: "Vallis Surveillance Drone",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusDroneAttackAgent": {
    name: "Terra Attack Drone",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusEliteSpacemanAgent": { name: "Terra Crewman", scans: 5 },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusHeavyEliteSpacemanAgent": {
    name: "Terra Elite Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusLaserCannonBipedAgent": { name: "Terra MOA", scans: 10 },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusLaserDiscBipedAgent": {
    name: "Terra Anti MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusShieldDroneAgent": {
    name: "Terra Shield Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusShockwaveBipedAgent": {
    name: "Terra Shockwave MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusShotgunSpacemanAgent": {
    name: "Terra Plasmor Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusSniperSpacemanAgent": {
    name: "Terra Sniper Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusSpacemanCarrierAgent": {
    name: "Corpus Power Carrier (Orb Vallis)",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/VenusSuicideDroneAgent": {
    name: "Terra Oxium Osprey",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Vip/VenusVipDualPistolSpacemanAgent": {
    name: "Corpus Cestra Target",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Vip/VenusVipPowerSpacemanAgent": {
    name: "Corpus Trencher Target",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Vip/VenusVipShotgunSpacemanAgent": {
    name: "Corpus Supra Target",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Venus/Vip/VenusVipSniperSpacemanAgent": {
    name: "Corpus Sniper Target",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Vip/AladV/AladBossAgent": { name: "Alad V", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Vip/Ambulas/AmbulasDropshipAgent": {
    name: "Condor Storm Dropship",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Corpus/Vip/Ambulas/AmbulasHackingDrone": {
    name: "Remech Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Vip/Ambulas/BossAmbulasRangedAgent": { name: "Ambulas", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Vip/Arachnoid/ArachnoidCamperAvatar": {
    name: "Profit-Taker Orb",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Vip/Arachnoid/ArachnoidCamperTerraAgent": {
    name: "Exploiter Orb",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Vip/Arachnoid/ArachnoidCoolantAgent": {
    name: "Coolant Raknoid",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Corpus/Vip/Arachnoid/ArachnoidHungerAgent": {
    name: "Scyto Raknoid",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Vip/Arachnoid/ArachnoidMicroAgent": {
    name: "Mite Raknoid",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Vip/Arachnoid/ArachnoidWraithAgent": {
    name: "Kyta Raknoid",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Vip/Hyena/HyenaElecAgent": { name: "Hyena TH", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Vip/Hyena/HyenaFireAgent": { name: "Hyena NG", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Vip/Hyena/HyenaGunAgent": { name: "Hyena PB", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Vip/Hyena/HyenaIceAgent": { name: "Hyena LN2", scans: 3 },
  "/Lotus/Types/Enemies/Corpus/Vip/InfestedAladV/InfestedAladBossAgent": {
    name: "Mutalist Alad V",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Corpus/Zariman/CrpInterrupterAgent": {
    name: "Derivator Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/CorpusChampions/TeamA/CCTeamAHeavyAgent": { name: "Ved Xol", scans: 3 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamA/CCTeamARifleAgent": { name: "Nako Xol", scans: 5 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamA/CCTeamASkateAgent": { name: "Pelna Cade", scans: 3 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamA/CCTeamAZanukaAgent": {
    name: "Lockjaw & Sol",
    scans: 3,
  },
  "/Lotus/Types/Enemies/CorpusChampions/TeamB/CCTeamBDisruptorAgent": {
    name: "Jad Teran",
    scans: 3,
  },
  "/Lotus/Types/Enemies/CorpusChampions/TeamB/CCTeamBHyenaAgent": { name: "Azoth", scans: 3 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamB/CCTeamBOspreyAgent": { name: "Raptor Rx", scans: 5 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamB/CCTeamBRiotMoaAgent": { name: "Auditor", scans: 5 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamC/CCTeamCDeceptionAgent": { name: "Jen Dro", scans: 5 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamC/CCTeamCMoaAgent": { name: "M-W.A.M.", scans: 5 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamC/CCTeamCSimplifiedHackerAgent": {
    name: "Derim Zahn",
    scans: 5,
  },
  "/Lotus/Types/Enemies/CorpusChampions/TeamC/CCTeamCStealthAgent": { name: "Tia Mayn", scans: 5 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamD/CCTeamDBusterAAgent": {
    name: "Armis Ulta",
    scans: 3,
  },
  "/Lotus/Types/Enemies/CorpusChampions/TeamD/CCTeamDBusterBAgent": {
    name: "Dru Pesfor",
    scans: 3,
  },
  "/Lotus/Types/Enemies/CorpusChampions/TeamD/CCTeamDBusterCAgent": { name: "Rana Del", scans: 3 },
  "/Lotus/Types/Enemies/CorpusChampions/TeamD/CCTeamDOspreyAgent": { name: "002-ER", scans: 5 },
  "/Lotus/Types/Enemies/Corrupted/CorruptedBeastMaster": {
    name: "Corrupted Drahk Master",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Duviri/Jackal/QuadRobotAgentDuviri": { name: "Corrupted Jackal", scans: 5 },
  "/Lotus/Types/Enemies/Duviri/PaxDuviricus/PaxDuviricusDungeonEncounterAgent": {
    name: "Kullervo (Boss)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Entrati/Doppelganger/EntratiDoppelgangerAgent": {
    name: "Mocking Whisper",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Entrati/Doppelganger/EntratiDoppelgangerRangedAgent": {
    name: "Scathing Whisper",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/Avatars/CameraDroneAvatar": {
    name: "Sensor Regulator",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/Avatars/NightwatchHeavyGunnerAvatar": {
    name: "Nightwatch Bombard",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/BeastMaster": { name: "Drahk Master", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/BladeSawman": { name: "Butcher", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/BlowtorchSawman": { name: "Flameblade", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/CameraDroneAgentOrokin": {
    name: "Orokin Spectator",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/CarrierJetpack": { name: "Hellion Power Carrier", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/CarrierRifleLancer": {
    name: "Grineer Power Carrier",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/CatMaster": { name: "Hyekka Master", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/CombatCatbrowAgent": { name: "Hyekka", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/CombatKubrowAgent": { name: "Drahk", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/EliteRifleLancer": { name: "Elite Lancer", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/EliteShieldLancer": {
    name: "Elite Shield Lancer",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/EviseratorLancer": { name: "Eviscerator", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/FlameLancer": { name: "Scorch", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/GrineerCharger": { name: "Bailiff", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/GrineerFemale": { name: "Ballista", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/GrineerMeleeStaffAgent": { name: "Guardsman", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/GrineerRollingDrone": { name: "Roller", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/GrineerWorker": { name: "Drudge Foreman", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/GrineerWorkerC": { name: "Drudge Scrapper", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/IncendiaryBombard": { name: "Napalm", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/JetpackHeavyMarine": { name: "Nightwatch Reaver", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/JetpackMarine": { name: "Hellion", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/JetpackMeleeMarine": { name: "Sprag", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/JetpackSniper": { name: "Ven'kra Tel", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/KelaRollingDrone": { name: "Armored Roller", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/MacheteWoman": { name: "Scorpion", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/ManicGrineer": { name: "Grineer Manic", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/ManicRocketBombard": { name: "Manic Bombard", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/MinigunBombard": { name: "Heavy Gunner", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/NightwatchCatMaster": {
    name: "Nightwatch Hyekka Master",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/NightwatchFlamebladeSawman": {
    name: "Nightwatch Flameblade",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/NightwatchGrineerCharger": {
    name: "Nightwatch Bailiff",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/NightwatchGrineerMarinePistol": {
    name: "Nightwatch Seeker",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/NightwatchHeavyGunner": {
    name: "Nightwatch Gunner",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/NightwatchManic": { name: "Nightwatch Manic", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/NightwatchPowerfist": {
    name: "Nightwatch Powerclaw",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/NightwatchRifleLancer": {
    name: "Nightwatch Lancer",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/NightwatchShieldLancer": {
    name: "Nightwatch Brunt Lancer",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/AIWeek/PistonSawman": { name: "Powerfist", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/RifleLancer": { name: "Lancer", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/RocketBombard": { name: "Bombard", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/RollerAutoTurret": { name: "Roller Sentry", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/ShieldLancer": { name: "Shield Lancer", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/ShotgunLancer": { name: "Trooper", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/AIWeek/StickyRollingDrone": { name: "Latcher", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/ChemStrike/ChemStrikeNoxAgent": { name: "Nox", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/DeathSquad/DeathSquadA": { name: "Vem Tabook", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/DeathSquad/DeathSquadB": { name: "Leekter", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/DeathSquad/DeathSquadC": { name: "Shik Tal", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Desert/BladeSawman": { name: "Arid Butcher", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Desert/EliteRifleLancer": { name: "Elite Arid Lancer", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Desert/EvisceratorLancer": { name: "Arid Eviscerator", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Desert/GrineerMarinePistol": { name: "Arid Seeker", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Desert/JetpackMarine": { name: "Arid Hellion", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Desert/MinigunBombard": { name: "Arid Heavy Gunner", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Desert/RifleLancer": { name: "Arid Lancer", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Desert/ShotgunLancer": { name: "Arid Trooper", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/Disruption/DemoDevourerAgent": {
    name: "Demolisher Devourer",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Disruption/DemoExpiredAgent": {
    name: "Demolisher Expired",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Disruption/DisruptionCharger": {
    name: "Demolisher Bailiff",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Disruption/DisruptionMinigunBombard": {
    name: "Demolisher Heavy Gunner",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Disruption/DisruptionNoxAgent": {
    name: "Demolisher Nox",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Disruption/DisruptionRoyalGuardAgent": {
    name: "Demolisher Kuva Guardian",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonAutoTurretAgent": {
    name: "Akkalak Turret",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonAutoTurretAgentMortar": {
    name: "Mordda Turret",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonAutoTurretAgentRocket": {
    name: "Vruush Turret",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonBladeSawman": { name: "Tusk Butcher", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonBlowtorchSawman": {
    name: "Tusk Flameblade",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonEliteRifleLancer": {
    name: "Tusk Elite Lancer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonEviseratorLancer": {
    name: "Tusk Eviscerator",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonGrineerFemale": { name: "Tusk Ballista", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonGrineerMarinePistol": {
    name: "Tusk Seeker",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonGrineerRollingDrone": {
    name: "Tusk Roller",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonIncendiaryBombard": {
    name: "Tusk Napalm",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonJetpackMarine": { name: "Tusk Hellion", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonJetpackMelee": { name: "Tusk Reaver", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonMinigunBombard": {
    name: "Tusk Heavy Gunner",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonMortarBombard": {
    name: "Tusk Mortar Bombard",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonPredator": { name: "Tusk Predator", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonRifleLancer": { name: "Tusk Lancer", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonRocketBombard": { name: "Tusk Bombard", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonShieldLancer": {
    name: "Tusk Shield Lancer",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonShotgunLancer": { name: "Tusk Trooper", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/Eidolon/EidolonSkiffPilotAgent": {
    name: "Dargyn Pilot",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/GrineerBomber/GrineerBomberAvatar": {
    name: "Tusk Ogma",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/GrineerDropship/GrineerBigDropshipAgent": {
    name: "Tusk Bolkor",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/GrineerDropship/GrineerDropshipAgent": {
    name: "Tusk Firbolg",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/GrineerSkiff/GrineerShieldSkiffAgent": {
    name: "Tusk Shield Dargyn",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/GrineerSkiff/GrineerSkiffAgent": {
    name: "Tusk Dargyn",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/Vip/Avatars/EidolonVipSniperAvatar": {
    name: "Recon Commander",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/Vip/EidolonVipGruntAgent": {
    name: "Plains Commander",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/Vip/EidolonVipGruntDroneAgent": {
    name: "Tusk Carabus",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/Vip/EidolonVipPilotAgent": {
    name: "Aerial Commander",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/Vip/EidolonVipSkiffAgent": {
    name: "Tusk Command Dargyn",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Eidolon/VomvalystLure/EidolonVomLureAgent": {
    name: "Eidolon Lure",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Forest/BladeSawman": { name: "Frontier Butcher", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Forest/EliteRifleLancer": {
    name: "Elite Frontier Lancer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Forest/EvisceratorLancer": {
    name: "Frontier Eviscerator",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Forest/GrineerCharger": { name: "Frontier Bailiff", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Forest/GrineerMarinePistol": { name: "Frontier Seeker", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Forest/JetpackMarine": { name: "Frontier Hellion", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Forest/MinigunBombard": { name: "Frontier Heavy Gunner", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Forest/RifleLancer": { name: "Frontier Lancer", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Forest/ShotgunLancer": { name: "Frontier Trooper", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/Fortress/Avatars/FortressSkiff": { name: "Kuva Dargyn", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressBeastMaster": {
    name: "Kuva Drahk Master",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressBladeSawman": { name: "Kuva Butcher", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressBlowtorchSawman": {
    name: "Kuva Flameblade",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressCatMaster": {
    name: "Kuva Hyekka Master",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressCombatCatbrowAgent": {
    name: "Kuva Hyekka",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressCombatKubrowAgent": {
    name: "Kuva Drahk",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressEliteRifleLancer": {
    name: "Kuva Elite Lancer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressEviseratorLancer": {
    name: "Kuva Eviscerator",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressFlameLancer": { name: "Kuva Scorch", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressGrineerCharger": { name: "Bailiff", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressGrineerFemale": {
    name: "Kuva Ballista",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressGrineerMarinePistol": {
    name: "Kuva Seeker",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressGrineerRollingDrone": {
    name: "Kuva Roller",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressIncendiaryBombard": {
    name: "Kuva Napalm",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressJetpackMarine": { name: "Kuva Hellion", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressMacheteWoman": {
    name: "Kuva Scorpion",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressMinigunBombard": {
    name: "Kuva Heavy Gunner",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressPistonSawman": {
    name: "Kuva Powerclaw",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressRifleLancer": { name: "Kuva Lancer", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressRocketBombard": { name: "Kuva Bombard", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressShieldLancer": {
    name: "Kuva Shield Lancer",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Fortress/FortressShotgunLancer": {
    name: "Kuva Trooper",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Ghouls/GhoulDevourerAgent": { name: "Ghoul Devourer", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Ghouls/GhoulDrillAgent": { name: "Ghoul Auger", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Ghouls/GhoulExpiredAgent": { name: "Ghoul Expired", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Ghouls/GhoulSawmanAgent": { name: "Ghoul Rictus", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/Ghouls/Vip/GhoulDrillVipAgent": {
    name: "Ghoul Auger Alpha",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Ghouls/Vip/GhoulSawmanVipAgent": {
    name: "Ghoul Rictus Alpha",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/GrineerAutoTurretStaticAgent": { name: "Senta Turret", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/GrineerMarineLeader": { name: "Commander", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/GrineerMarinePistol": { name: "Seeker", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/InfestedMicroPlanet/GrineerShotgunSurvivorAgent": {
    name: "Lancer Survivor",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/InfestedMicroPlanet/GrineerShotgunSurvivorAvatar": {
    name: "Trooper Survivor",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Narmer/Avatars/NarmerRifleLancerAvatar": {
    name: "Narmer Lancer",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Narmer/NarmerEidolonAlarmDroneAgent": {
    name: "Tusk Seeker Drone",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/AdmiralLightningAgent": {
    name: "Lektro Commander",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/AdmiralPoisonAgent": { name: "Blite Captain", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/RailJack/Avatars/AdmiralFireAvatar": {
    name: "Pyr Captain",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/Avatars/AdmiralIceAvatar": {
    name: "Glacik Commander",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSBoardingDemoAgent": {
    name: "Exo Raider",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSBoardingMeleeAgent": {
    name: "Exo Raider Carver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSBoardingShotgunAgent": {
    name: "Exo Raider Eviscerator",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSCaptainHeavyAgent": {
    name: "Exo Gokstad Officer",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSCaptainRollerTurretAgent": {
    name: "Exo Roller Sentry",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSCrewBladeAgent": {
    name: "Exo Butcher",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSCrewEliteRifleAgent": {
    name: "Exo Elite Lancer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSCrewEvisceratorAgent": {
    name: "Exo Eviscerator",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSCrewFlameAgent": {
    name: "Exo Supressor",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/DeepSpace/GrnDSPilotAgent": {
    name: "Exo Gokstad Pilot",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnBoardingDemoAgent": { name: "Gyre Raider", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnBoardingMeleeAgent": {
    name: "Gyre Raider Carver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnBoardingShotgunAgent": {
    name: "Gyre Raider Eviscerator",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnCaptainHeavyAgent": {
    name: "Kosma Gokstad Officer",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnCaptainRollerTurretAgent": {
    name: "Kosma Roller Sentry",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnCrewBladeAgent": { name: "Kosma Butcher", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnCrewEliteRifleAgent": {
    name: "Kosma Elite Lancer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnCrewEvisceratorAgent": {
    name: "Kosma Eviscerator",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnCrewFlameAgent": { name: "Kosma Supressor", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/RailJack/GrnPilotAgent": { name: "Kosma Gokstad Pilot", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/RailJack/Saturn/GrnSaturnBoardingShotgunAgent": {
    name: "Gyre Eviscerator",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/Saturn/GrnSaturnCaptainHeavyAgent": {
    name: "Gyre Gokstad Officer",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/Saturn/GrnSaturnCaptainRollerTurretAgent": {
    name: "Gyre Roller Sentry",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/Saturn/GrnSaturnCrewBladeAgent": {
    name: "Gyre Butcher",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/Saturn/GrnSaturnCrewEliteRifleAgent": {
    name: "Gyre Elite Lancer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/Saturn/GrnSaturnCrewFlameAgent": {
    name: "Gyre Supressor",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/RailJack/Saturn/GrnSaturnPilotAgent": {
    name: "Gyre Gokstad Pilot",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/SeaLab/BladeSawman": { name: "Drekar Butcher", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/SeaLab/EliteRifleLancer": { name: "Drekar Elite Lancer", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/SeaLab/EvisceratorLancer": { name: "Drekar Eviscerator", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/SeaLab/GrineerFemaleHeavy": {
    name: "Drekar Heavy Gunner",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/SeaLab/GrineerFemaleMachete": {
    name: "Drekar Scorpion",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/SeaLab/GrineerFemaleSniper": { name: "Drekar Ballista", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/SeaLab/GrineerMarinePistol": { name: "Drekar Seeker", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/SeaLab/JetpackMarine": { name: "Drekar Hellion", scans: 5 },
  "/Lotus/Types/Enemies/Grineer/SeaLab/RifleLancer": { name: "Drekar Lancer", scans: 20 },
  "/Lotus/Types/Enemies/Grineer/SeaLab/SeaLabManicGrineer": { name: "Drekar Manic", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/SeaLab/SeaLabManicRocketBombard": {
    name: "Drekar Manic Bombard",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/SeaLab/ShotgunLancer": { name: "Drekar Trooper", scans: 10 },
  "/Lotus/Types/Enemies/Grineer/SpecialEvents/GrineerArtificer": { name: "Artificer", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/SpecialEvents/SurveillanceDroneAvatar": {
    name: "Regulator",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Thumper/ThumperAgent": { name: "Tusk Thumper", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Thumper/ThumperLargeAgent": { name: "Tusk Thumper Doma", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Thumper/ThumperMedAgent": { name: "Tusk Thumper Bull", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Vip/BossLechKrilAgent": { name: "Lt Lech Kril", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Vip/CaptainVorBossAgent": { name: "Captain Vor", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Vip/GrineerRoyalGuard/GrineerRoyalGuardAgent": {
    name: "Kuva Guardian",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Vip/Hek/HekBipedAgent": { name: "Vay Hek Terra Frame", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Vip/Hek/HekDroneStage1Agent": {
    name: "Councilor Vay Hek",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Vip/Hek/PropDrones/HekPropCCDroneAgent": {
    name: "Disruptor Drone",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Vip/Hek/PropDrones/StrikeDroneAvatar": {
    name: "Orbital Strike Drone",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Grineer/Vip/RoyalJester/RoyalJesterAvatar": {
    name: "Kuva Jester",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Grineer/Vip/SargasRuk/SargasRukBossAgent": {
    name: "General Sargas Ruk",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Grineer/Vip/TylRegor/TylRegorAgent": { name: "Tyl Regor", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Vip/VorRework/VorArenaTurret/VorArenaTurretAgent": {
    name: "Cannon Battery",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Grineer/Vip/VorTwo/VorTwoBossAgent": { name: "Corrupted Vor", scans: 3 },
  "/Lotus/Types/Enemies/Grineer/Zariman/GrnAntiWarframeAgent": { name: "Kuva Trokarian", scans: 3 },
  "/Lotus/Types/Enemies/GrineerChampions/GrineerChampionBeastmasterAgent": {
    name: "Executioner Zura",
    scans: 5,
  },
  "/Lotus/Types/Enemies/GrineerChampions/GrineerChampionChargerAgent": {
    name: "Executioner Garesh",
    scans: 5,
  },
  "/Lotus/Types/Enemies/GrineerChampions/GrineerChampionEngineerAgent": {
    name: "Executioner Reth",
    scans: 5,
  },
  "/Lotus/Types/Enemies/GrineerChampions/GrineerChampionGruntAgent": {
    name: "Executioner Nok",
    scans: 5,
  },
  "/Lotus/Types/Enemies/GrineerChampions/GrineerChampionHealerAgent": {
    name: "Executioner Dok Thul",
    scans: 5,
  },
  "/Lotus/Types/Enemies/GrineerChampions/GrineerChampionHeavyAgent": {
    name: "Executioner Dhurnam",
    scans: 5,
  },
  "/Lotus/Types/Enemies/GrineerChampions/GrineerChampionJetpackAgent": {
    name: "Executioner Vay Molta",
    scans: 5,
  },
  "/Lotus/Types/Enemies/GrineerChampions/GrineerChampionSniperAgent": {
    name: "Executioner Harkonar",
    scans: 5,
  },
  "/Lotus/Types/Enemies/GrineerChampions/GrineerChampionTankAgent": {
    name: "Executioner Gorth",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Ancients/AncientAvatar": {
    name: "Ancient Disruptor",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Ancients/DiseasedAncient": {
    name: "Brood Mother",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Ancients/HealingAncient": {
    name: "Ancient Healer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Ancients/ProtectorAncient": {
    name: "Ancient Protector",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Ancients/SpawningAncient": { name: "Boiler", scans: 5 },
  "/Lotus/Types/Enemies/Infested/AiWeek/Ancients/SpawningAncientMiniboss": {
    name: "Arcane Boiler",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Ancients/ToxicAncient": { name: "Toxic Ancient", scans: 3 },
  "/Lotus/Types/Enemies/Infested/AiWeek/Crawlers/GraspingCrawler": {
    name: "Nauseous Crawler",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Crawlers/GrenadeCrawler": {
    name: "Lobber Crawler",
    scans: 30,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Crawlers/LightningCrawler": {
    name: "Electric Crawler",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Crawlers/MeleeCrawler": { name: "Crawler", scans: 30 },
  "/Lotus/Types/Enemies/Infested/AiWeek/Crawlers/NoxiousCrawler": {
    name: "Toxic Crawler",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Emissary/AncientShellAgent": {
    name: "Deimos Therid",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Emissary/AncientTankAgent": {
    name: "Leaping Thrasher",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Emissary/InfestedJetpackAgent": {
    name: "Undying Flyer",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/GreyStrain/BoneBlade/BoneBladeAgent": {
    name: "Deimos Jugulus",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/GreyStrain/Femur/InfestedFemurAgent": {
    name: "Deimos Saxum",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/InfestedDrones/CellCarrierDroneAgent": {
    name: "Mutalist Osprey Carrier",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/InfestedDrones/InfestedAttackDroneAgent": {
    name: "Venin Mutalist",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/InfestedDrones/PoisonDroneAgent": {
    name: "Mutalist Osprey",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/InfestedMoas/NaniteCloudBipedAgent": {
    name: "Swarm Mutalist MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/InfestedMoas/SlowBombBipedAgent": {
    name: "Tar Mutalist MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Quadrupeds/Juggernaut": { name: "Juggernaut", scans: 3 },
  "/Lotus/Types/Enemies/Infested/AiWeek/Quadrupeds/JuggernautBoss": {
    name: "Juggernaut Behemoth",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Quadrupeds/Quadruped": { name: "Charger", scans: 20 },
  "/Lotus/Types/Enemies/Infested/AiWeek/Quadrupeds/QuadrupedColonist": {
    name: "Carrion Charger",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/Quadrupeds/RusherAgent": { name: "Maggot", scans: 30 },
  "/Lotus/Types/Enemies/Infested/AiWeek/Runners/LeapingRunner": { name: "Leaper", scans: 30 },
  "/Lotus/Types/Enemies/Infested/AiWeek/Runners/MeleeRunner": { name: "Runner", scans: 30 },
  "/Lotus/Types/Enemies/Infested/AiWeek/Runners/SuicideRunner": {
    name: "Volatile Runner",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/WeaveMutalist/DecodeSpawn": {
    name: "Zealoid Bastion",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/AiWeek/WeaveMutalist/WeaveMutalist": {
    name: "Zealoid Prelate",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/Disruption/DisruptionAncientTankAgent": {
    name: "Demolisher Thrasher",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/Disruption/DisruptionBoilerAgent": {
    name: "Demolisher Boiler",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/Disruption/DisruptionJuggernautAgent": {
    name: "Demolisher Juggernaut",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/Disruption/DisruptionQuadrupedAgent": {
    name: "Demolisher Charger",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Infested/Eidolon/EidolonLephantisAgent": { name: "Hemocyte", scans: 3 },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/AncientTankMicroPlanetAgent": {
    name: "Deimos Leaping Thrasher",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Ashen/AshenAgent": {
    name: "Deimos Carnis",
    scans: 30,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Ashen/AshenBigAgent": {
    name: "Deimos Carnis Rex",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/CellCarrierDroneMicroPlanet": {
    name: "Deimos Mutalist Osprey Carrier",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/DeployableSpacemanResearcher": {
    name: "Latrox Une",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/DiseasedAncientMicroPlanet": {
    name: "Deimos Brood Mother",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Drones/Tendril/InfestedTendrilDroneAgent": {
    name: "Deimos Tendril Drone",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Dropship/InfestedBigDropshipAgent": {
    name: "Deimos Genetrix",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/FemurAssassinateTargetAgent": {
    name: "Deimos Saxum Rex",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/HealingAncientMicroPlanet": {
    name: "Deimos Ancient Healer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/InfestedAttackDroneMicroPlanet": {
    name: "Deimos Venin Mutalist",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/JuggernautMicroPlanetCasual": {
    name: "Deimos Juggernaut",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/JuggernautMicroPlanetEscort": {
    name: "Polyp-Hog Juggernaut",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/LeapingSuicideRunner": {
    name: "Deimos Leaper",
    scans: 30,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/MeleeMicroPlanetRunner": {
    name: "Deimos Runner",
    scans: 30,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/NaniteCloudBipedMicroPlanet": {
    name: "Deimos Swarm Mutalist MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Oni/InfestedJetpackMicroPlanetOni": {
    name: "Deimos Undying Flyer",
    scans: 10,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/QuadrupedMicroPlanet": {
    name: "Deimos Charger",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Splitter/SplitterAgent": {
    name: "Mitosid",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Splitter/SplitterAgentVIP": {
    name: "Mitosid Rex",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Splitter/SplitterSplitAgent": {
    name: "Basal Diploid",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Splitter/SplitterSplitAgentVIP": {
    name: "Basal Diploid Rex",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Splitter/SplitterTopSplitAgent": {
    name: "Feral Diploid",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/InfestedMicroplanet/Splitter/SplitterTopSplitAgentVIP": {
    name: "Feral Diploid Rex",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/SpecialEvents/ArloZealotDual/ArloZealotDualSwordGunAgent": {
    name: "Zealot Proselytizer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/SpecialEvents/ArloZealotGunAgent": {
    name: "Zealot Herald",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/SpecialEvents/ArloZealotSwordAgent": {
    name: "Zealot Baptizer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Infested/Vip/GolemFullAgent": { name: "Lephantis", scans: 3 },
  "/Lotus/Types/Enemies/Infested/Vip/J3Golem/JuniorGolemSpaceAgent": {
    name: "Jordas Golem",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Infested/Vip/QuadrupedVIP": { name: "Phorid", scans: 3 },
  "/Lotus/Types/Enemies/KuvaLich/KuvaLarvlingAgent": { name: "Kuva Larvling", scans: 5 },
  "/Lotus/Types/Enemies/KuvaLich/KuvaLarvlingFemaleAgent": { name: "Kuva Larvling", scans: 5 },
  "/Lotus/Types/Enemies/ManInTheWall/HandBomber/HandBomberAgent": {
    name: "The Anatomizer",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/Murmur/MITWMurmurAgent": {
    name: "The Unseeing Herald",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechBonewindow/CoHNecramechBonewidowAgent": {
    name: "Rogue Bonewidow (Descendia)",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechBonewindow/NecramechBonewidowAgent": {
    name: "Rogue Bonewidow",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechBonewindow/NecramechBonewidowDisruptionAgent": {
    name: "Demolisher Bonewidow",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechMelee/AlchemyNecramechMeleeAgent": {
    name: "Elementa Arcocanid",
    scans: 20,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechMelee/NecramechMeleeAgent": {
    name: "Rogue Arcocanid",
    scans: 20,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechRanged/AlchemyNecramechRangedAgent": {
    name: "Elementa Culverin",
    scans: 20,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechRanged/NecramechRangedAgent": {
    name: "Rogue Culverin",
    scans: 20,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechVoidRig/CoHNecramechVoidRigAgent": {
    name: "Rogue Voidrig (Descendia)",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechVoidRig/NecramechVoidRigAgent": {
    name: "Rogue Voidrig",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/NecramechVoidRig/NecramechVoidRigDisruptionAgent": {
    name: "Demolisher Voidrig",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/Octopede/Arm/ArmTurret/MITWOctopedeArmTurretAgent": {
    name: "Hurling Fragment",
    scans: 40,
  },
  "/Lotus/Types/Enemies/ManInTheWall/Octopede/Arm/ExplosiveArm/MITWOctopedeExplosiveArmAgent": {
    name: "Rupturing Fragment",
    scans: 40,
  },
  "/Lotus/Types/Enemies/ManInTheWall/Octopede/Arm/MITWOctopedeArmAgent": {
    name: "Shuffling Fragment",
    scans: 40,
  },
  "/Lotus/Types/Enemies/ManInTheWall/Octopede/Leg/BipedalLegs/MITWOctopedeBipedalLegsAgent": {
    name: "Lumbering Fragment",
    scans: 5,
  },
  "/Lotus/Types/Enemies/ManInTheWall/Octopede/MITWOctopedeAgent": {
    name: "The Fragmented",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/Slinky/MITWSlinkyAgent": { name: "The Hollow Vein", scans: 3 },
  "/Lotus/Types/Enemies/ManInTheWall/TreasureBox/MITWTreasureBoxAgent": {
    name: "Gruzzling",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/Triangle/MITWSupportTriangleAgent": {
    name: "The Severed Warden",
    scans: 3,
  },
  "/Lotus/Types/Enemies/ManInTheWall/VialCarryDrone/VialDroneAgent": {
    name: "Vitriol Necramite",
    scans: 40,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoBaseHeavyBipedAgent": {
    name: "Scrofa Drover Bursa",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoEliteSpacemanAgent": {
    name: "Scrofa Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoFlyingAttackAgent": {
    name: "Scrofa Attack Drone",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoFlyingSupportAgent": {
    name: "Scrofa Shield Osprey",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoHeavyEliteSpacemanAgent": {
    name: "Scrofa Elite Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoLabMeleeHeavyAgent": {
    name: "Scrofa Legionary",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoLaserCannonBipedAgent": {
    name: "Scrofa Laser MOA",
    scans: 10,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoMeleeHeavyAgent": {
    name: "Scrofa Heavy Trencher",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoMineDroneAgent": {
    name: "Scrofa Mine Osprey",
    scans: 10,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoMiniArachnoidAgent": {
    name: "Scrofa Mite Raknoid",
    scans: 20,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoPlantMeleeHeavyAgent": {
    name: "Scrofa Lythrum Raknoid",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoRailgunBipedAgent": {
    name: "Scrofa Railgun Moa",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoRangedHeavyAgent": {
    name: "Scrofa Grenadier Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoShockwaveBipedAgent": {
    name: "Scrofa Shockwave Moa",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoShotgunSpacemanAgent": {
    name: "Scrofa Plasmor Crewman",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoSniperAgent": {
    name: "Scrofa Sniper Ranger",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Agents/NokkoSuicideBipedAgent": {
    name: "Scrofa Decoy MOA",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Vip/NokkoBaseCorpusVIPAgent": {
    name: "Scrofa Armaments Director",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Vip/NokkoBaseRaknoidVIPAgent": {
    name: "Scrofa Joro Raknoid",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Vip/NokkoColonyVIPAgentB": {
    name: "Scrofa Strike Director",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Vip/NokkoColonyVIPAvatarA": {
    name: "Scrofa Demolition Director",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Vip/NokkoLabVIPAgent": {
    name: "Scrofa Research Chief",
    scans: 3,
  },
  "/Lotus/Types/Enemies/NokkoColony/Vip/NokkoPlantVIPAgent": {
    name: "Scrofa Latro Raknoid",
    scans: 5,
  },
  "/Lotus/Types/Enemies/NokkoColony/Vip/NokkoTrappedChestVIPAgent": {
    name: "Scrofa Energy Chief",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Orokin/Entrati/EntratiTech/NechroTech/NechroTechEnemyAgent": {
    name: "Rogue Voidrig",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Orokin/Entrati/EntratiTech/Thanotech/ThanoTechEnemyAgent": {
    name: "Deimos Rogue Bonewidow",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Orokin/Gamemodes/CorruptedWardenAgent": {
    name: "Corrupted Warden",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Orokin/OrokinAutoTurretAgent": { name: "Orokin Sentry", scans: 20 },
  "/Lotus/Types/Enemies/Orokin/OrokinBladeSawman": { name: "Corrupted Butcher", scans: 20 },
  "/Lotus/Types/Enemies/Orokin/OrokinDroneAttackAgent": { name: "Corrupted Drone", scans: 5 },
  "/Lotus/Types/Enemies/Orokin/OrokinHealingAncient": { name: "Corrupted Ancient", scans: 5 },
  "/Lotus/Types/Enemies/Orokin/OrokinMinigunBombard": { name: "Corrupted Heavy Gunner", scans: 3 },
  "/Lotus/Types/Enemies/Orokin/OrokinMoaBipedAgent": { name: "Corrupted MOA", scans: 5 },
  "/Lotus/Types/Enemies/Orokin/OrokinNullifySpacemanAgent": {
    name: "Corrupted Nullifier",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Orokin/OrokinRocketBombard": { name: "Corrupted Bombard", scans: 3 },
  "/Lotus/Types/Enemies/Orokin/OrokinShieldDroneAgent": { name: "Orokin Drone", scans: 20 },
  "/Lotus/Types/Enemies/Orokin/RifleLancer": { name: "Corrupted Lancer", scans: 20 },
  "/Lotus/Types/Enemies/Orokin/RifleSpacemanAgent": { name: "Corrupted Crewman", scans: 20 },
  "/Lotus/Types/Enemies/Quests/SandmanBoss/InarosGolemAgent": {
    name: "Tomb Protector Effigy",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Quests/SandmanBoss/SandmanBossAgent": { name: "Tomb Protector", scans: 1 },
  "/Lotus/Types/Enemies/Sentients/Aerolyst/SentientAerolystAgent": { name: "Aerolyst", scans: 5 },
  "/Lotus/Types/Enemies/Sentients/Brachiolyst/SentientBrachiolystAgent": {
    name: "Brachiolyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Condrix/SentientCondrixAgent": { name: "Condrix", scans: 20 },
  "/Lotus/Types/Enemies/Sentients/Condrix/SentientCondrixAgentMechEvent": {
    name: "Orphix",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Sentients/Dolicholyst/SentientDolicholystAgent": {
    name: "Summulyst",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Sentients/Eidolon/SentientEidolonGhostCasterAgent": {
    name: "Choralyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Eidolon/SentientTeralystAgent": {
    name: "Eidolon Teralyst",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Sentients/Eidolon/SentientTeralystBigAgent": {
    name: "Eidolon Gantulyst",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Sentients/Eidolon/SentientTeralystRainAgent": {
    name: "Eidolon Hydrolyst",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Sentients/Eidolon/SentientVomvalystAgent": {
    name: "Eidolon Vomvalyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Mimics/SentientTrooperMimicAgent": { name: "Mimic", scans: 5 },
  "/Lotus/Types/Enemies/Sentients/Ortholyst/SentientOrtholystAgent": {
    name: "Ortholyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Ropalolyst/SentientRopalolystAgent": {
    name: "Ropalolyst",
    scans: 3,
  },
  "/Lotus/Types/Enemies/Sentients/Scouts/ScoutAvatar": { name: "Oculyst", scans: 20 },
  "/Lotus/Types/Enemies/Sentients/Symbilyst/SentientSymbilystAgent": {
    name: "Symbilyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Troopers/SentientBaseTrooperAgent": {
    name: "Battalyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Troopers/SentientMeleeTrooperAgent": {
    name: "Conculyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Troopers/SentientMeleeTrooperNoPowersAgent": {
    name: "Tyro Conculyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Troopers/SentientTrooperNoPowersAgent": {
    name: "Tyro Battalyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Troopers/SentientVoidMeleeTrooperAgent": {
    name: "Decaying Conculyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Sentients/Troopers/SentientVoidTrooperAgent": {
    name: "Decaying Battalyst",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Shadowgrapher/InkframeCloneEnemyAgent": { name: "Follie", scans: 5 },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/CrewMan/JetCorpusNavAgent": {
    name: "Ranger",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/CrewMan/JetCorpusThreeNavAgent": {
    name: "Quanta Ranger",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/CrewMan/JetCorpusTwoNavAgent": {
    name: "Penta Ranger",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Drones/SwarmDrone": { name: "Locust Drone", scans: 10 },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Fighters/SpaceFighterChargeEliteAgent": {
    name: "Elite Taro Basilisk",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Fighters/SpaceFighterGoxAgent": {
    name: "Taro Gox",
    scans: 3,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Fighters/SpaceFighterLaserEliteAgent": {
    name: "Elite Taro Harpi",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Fighters/SpaceFighterPlasmaEliteAgent": {
    name: "Elite Taro Weaver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/FlakShipNavAgent": { name: "Corvette", scans: 5 },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/LaserShipNavAgent": { name: "Frigate", scans: 5 },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/CorpusIceSledAgent": {
    name: "Comet Shard",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/CorpusPodAgent": { name: "Gox", scans: 3 },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/CorpusRamSledAgent": {
    name: "Corpus Ramsled",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/DeepSpace/SpaceFighterDSChargeAgent": {
    name: "Orm Basilisk",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/DeepSpace/SpaceFighterDSChargeEliteAgent": {
    name: "Elite Orm Basilisk",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/DeepSpace/SpaceFighterDSGoxAgent": {
    name: "Orm Gox",
    scans: 3,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/DeepSpace/SpaceFighterDSLaserAgent": {
    name: "Orm Harpi",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/DeepSpace/SpaceFighterDSLaserEliteAgent": {
    name: "Elite Orm Harpi",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/DeepSpace/SpaceFighterDSPlasmaAgent": {
    name: "Orm Weaver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/DeepSpace/SpaceFighterDSPlasmaEliteAgent": {
    name: "Elite Orm Weaver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Neptune/SpaceFighterNeptuneChargeAgent": {
    name: "Axio Basilisk",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Neptune/SpaceFighterNeptuneChargeEliteAgent": {
    name: "Elite Axio Basilisk",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Neptune/SpaceFighterNeptuneGoxAgent": {
    name: "Axio Gox",
    scans: 3,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Neptune/SpaceFighterNeptuneLaserAgent": {
    name: "Axio Harpi",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Neptune/SpaceFighterNeptuneLaserEliteAgent": {
    name: "Elite Axio Harpi",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Neptune/SpaceFighterNeptunePlasmaAgent": {
    name: "Axio Weaver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Neptune/SpaceFighterNeptunePlasmaEliteAgent": {
    name: "Elite Axio Weaver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Pluto/SpaceFighterPlutoChargeAgent": {
    name: "Vorac Basilisk",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Pluto/SpaceFighterPlutoChargeEliteAgent": {
    name: "Elite Vorac Basilisk",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Pluto/SpaceFighterPlutoGoxAgent": {
    name: "Vorac Gox",
    scans: 3,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Pluto/SpaceFighterPlutoLaserEliteAgent": {
    name: "Elite Vorac Harpi",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Pluto/SpaceFighterPlutoPlasmaAgent": {
    name: "Vorac Weaver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/Pluto/SpaceFighterPlutoPlasmaEliteAgent": {
    name: "Elite Vorac Weaver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/SpaceFighterChargeAgent": {
    name: "Taro Basilisk",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/SpaceFighterLaserAgent": {
    name: "Taro Harpi",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Ships/SpaceFighterPlasmaAgent": {
    name: "Taro Weaver",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/SwarmShipNavAgent": { name: "Carrier", scans: 5 },
  "/Lotus/Types/Enemies/SpaceBattles/Corpus/Turrets/CorpusSpaceTurretAgent": {
    name: "Cannon Battery",
    scans: 10,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Grineer/Drones/GrineerSpaceDrone": { name: "Dreg", scans: 10 },
  "/Lotus/Types/Enemies/SpaceBattles/Grineer/Drones/LaserDrone": { name: "Lancer Dreg", scans: 10 },
  "/Lotus/Types/Enemies/SpaceBattles/Grineer/Drones/StasisDrone": {
    name: "Temporal Dreg",
    scans: 10,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Grineer/GrineerMissilePlatAvatar": {
    name: "Zeplen",
    scans: 3,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Grineer/Pods/CombatPod": { name: "Ogma", scans: 3 },
  "/Lotus/Types/Enemies/SpaceBattles/Grineer/Skiffs/GrineerSpaceMarine": {
    name: "Dargyn",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Grineer/Skiffs/MissileShieldSkiff": {
    name: "Shield-Hellion Dargyn",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Grineer/Skiffs/MissileSkiff": {
    name: "Hellion Dargyn",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Grineer/Skiffs/ShieldSkiff": {
    name: "Shield Dargyn",
    scans: 5,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Infested/GrenadeCarrierDrone": {
    name: "Mutalist Toxic Carrier",
    scans: 10,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Infested/InfestedAttackDrone": {
    name: "Attack Mutalist",
    scans: 20,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Infested/LightningCarrierDrone": {
    name: "Mutalist Lightning Carrier",
    scans: 20,
  },
  "/Lotus/Types/Enemies/SpaceBattles/Sentient/Fighters/SpaceFighterSntAssaultAgent": {
    name: "Ionyx",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Stalker/JadeStalkerAgent": { name: "Protector Stalker", scans: 3 },
  "/Lotus/Types/Enemies/Stalker/SentientStalkerAgent": { name: "Shadow Stalker", scans: 3 },
  "/Lotus/Types/Enemies/Stalker/StalkerAgent": { name: "Stalker", scans: 3 },
  "/Lotus/Types/Enemies/Tau/CoH/Bosses/CoHOraxiaEnemyAgent": {
    name: "Oraxia (Descendia)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/CoH/Bosses/CoHPaxDuviricusDungeonEncounterAgent": {
    name: "Kullervo (Descendia)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Dax/TauDaxArcher/AnarchTauDaxArcherAgent": {
    name: "Anarch Arcus",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Tau/Dax/TauDaxHeavyArch/AnarchTauDaxHeavyArchgunAgent": {
    name: "Anarch Libritor",
    scans: 5,
  },
  "/Lotus/Types/Enemies/Tau/Dax/TauDaxMedic/AnarchTauDaxMedicAgent": {
    name: "Anarch Capsarii",
    scans: 15,
  },
  "/Lotus/Types/Enemies/Tau/Dax/TauDaxNinja/AnarchTauDaxNinjaAgent": {
    name: "Anarch Tenebra",
    scans: 15,
  },
  "/Lotus/Types/Enemies/Tau/Dax/TauDaxSwordsman/AnarchTauDaxSwordsmanAgent": {
    name: "Anarch Gladius",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Tau/Grineer/TauGrineerLancer/AnarchTauGrineerLancerAgent": {
    name: "Anarch Grineer Lancer",
    scans: 20,
  },
  "/Lotus/Types/Enemies/Tau/Grineer/TauGrineerTrapper/AnarchTauGrineerTrapperAgent": {
    name: "Anarch Grineer Trapper",
    scans: 15,
  },
  "/Lotus/Types/Enemies/Tau/GuiltSentient/SentientGuiltBossAgent": { name: "Dactolyst", scans: 1 },
  "/Lotus/Types/Enemies/Tau/Monolyst/MonolystAgent": { name: "Dactolyst", scans: 1 },
  "/Lotus/Types/Enemies/Tau/Primes/Ash/AshPrimeBossAgent": {
    name: "Commandeered Ash Prime",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Ash/AshPrimeBossHardModeAgent": {
    name: "Commandeered Ash Prime (The Guilty)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Ash/AshPrimeTMWAgent": {
    name: "Commandeered Ash Prime (Field Boss)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Caliban/CalibanPrimeBossAgent": {
    name: "Commandeered Caliban Prime",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Caliban/CalibanPrimeBossHardModeAgent": {
    name: "Commandeered Caliban Prime (The Guilty)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Caliban/CalibanPrimeTMWAgent": {
    name: "Commandeered Caliban Prime (Field Boss)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Ember/EmberPrimeBossAgent": {
    name: "Commandeered Ember Prime",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Ember/EmberPrimeBossHardModeAgent": {
    name: "Commandeered Ember Prime (The Guilty)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Ember/EmberPrimeTMWAgent": {
    name: "Commandeered Ember Prime (Field Boss)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Mesa/MesaPrimeBossAgent": {
    name: "Commandeered Mesa Prime",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Mesa/MesaPrimeBossHardModeAgent": {
    name: "Commandeered Mesa Prime (The Guilty)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Mesa/MesaPrimeTMWAgent": {
    name: "Commandeered Mesa Prime (Field Boss)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Protea/ProteaPrimeBossAgent": {
    name: "Commandeered Protea Prime",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Protea/ProteaPrimeBossHardModeAgent": {
    name: "Commandeered Protea Prime (The Guilty)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Protea/ProteaPrimeTMWAgent": {
    name: "Commandeered Protea Prime (Field Boss)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Trinity/TrinityPrimeBossAgent": {
    name: "Commandeered Trinity Prime",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Volt/VoltPrimeBossAgent": {
    name: "Commandeered Volt Prime",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Volt/VoltPrimeBossHardModeAgent": {
    name: "Commandeered Volt Prime (The Guilty)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Tau/Primes/Volt/VoltPrimeTMWAgent": {
    name: "Commandeered Volt Prime (Field Boss)",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/FairyQuest/FairyQuestLokiAgent": {
    name: "Knave Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/FairyQuest/FairyQuestPaladinAvatar": {
    name: "Feyarch Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/FairyQuest/FairyQuestSarynAgent": {
    name: "Orphid Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/JunctionRework/MesaJunctionBossAvatar": {
    name: "Mesa Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/JunctionRework/VoltJunctionBossAvatar": {
    name: "Volt Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/OdaliskQuest/OdaliskQuestSpecterAgent": {
    name: "Protea Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/OraxiaEnemy/OraxiaEnemyAgent": { name: "Oraxia", scans: 1 },
  "/Lotus/Types/Enemies/TennoReplicants/OraxiaEnemy/OraxiaEnemySpiderlingAgent": {
    name: "Scuttler",
    scans: 5,
  },
  "/Lotus/Types/Enemies/TennoReplicants/OraxiaEnemy/OraxiaEnemySpiderlingAvatar": {
    name: "Scuttlers",
    scans: 5,
  },
  "/Lotus/Types/Enemies/TennoReplicants/OraxiaEnemy/OraxiaEnemySpiderlingSuicideAgent": {
    name: "Death Scuttler",
    scans: 5,
  },
  "/Lotus/Types/Enemies/TennoReplicants/OraxiaEnemy/OraxiaEnemySpiderlingSuicideAvatar": {
    name: "Death Scuttlers",
    scans: 5,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantBerserkerAgent": {
    name: "Valkyr Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantEmberAgent": {
    name: "Ember Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantExcaliburAvatar": {
    name: "Excalibur Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantFrostAgent": {
    name: "Frost Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantLokiAgent": {
    name: "Loki Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantMagAgent": {
    name: "Mag Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantNovaAgent": {
    name: "Nova Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantRhinoAgent": {
    name: "Rhino Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantSarynAgent": {
    name: "Saryn Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantTrinityAgent": {
    name: "Trinity Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/RelayBoss/TennoReplicantYinYangAvatar": {
    name: "Equinox Specter",
    scans: 1,
  },
  "/Lotus/Types/Enemies/TennoReplicants/SyndicateAllies/ColonyRescueAllies/ColonistRescueSteelMeridianAvatarA":
    { name: "Kavor Defector", scans: 3 },
  "/Lotus/Types/Enemies/TennoReplicants/TennoReplicantChromaAgent": { name: "Chroma", scans: 1 },
  "/Lotus/Types/Enemies/TennoReplicants/TennoReplicantGunslingerAgent": {
    name: "Infested Mesa",
    scans: 1,
  },
  "/Lotus/Types/Enemies/Water/Grineer/EelLancerAgent": { name: "Shock Draga", scans: 20 },
  "/Lotus/Types/Enemies/Water/Grineer/FrogLancerNavAgent": { name: "Draga", scans: 20 },
  "/Lotus/Types/Enemies/Water/Grineer/SquidLancerAgent": { name: "Darek Draga", scans: 20 },
  "/Lotus/Types/Enemies/Water/Grineer/WaterMineDrone": { name: "Sikula", scans: 10 },
  "/Lotus/Types/Enemies/WF1999Infested/InfestedAncient/InfestedAncient1999Agent": {
    name: "Techrot Obsolyte",
    scans: 5,
  },
  "/Lotus/Types/Enemies/WF1999Infested/InfestedBabau/DeviationInfestedBabau1999Agent": {
    name: "Techrot Babau (Temporal Archimedea Survival)",
    scans: 5,
  },
  "/Lotus/Types/Enemies/WF1999Infested/InfestedBabau/InfestedBabau1999Agent": {
    name: "Techrot Babau",
    scans: 3,
  },
  "/Lotus/Types/Enemies/WF1999Infested/InfestedMaggot/InfestedMaggot1999Agent": {
    name: "Techrot Miasmite",
    scans: 40,
  },
  "/Lotus/Types/Enemies/WF1999Infested/InfestedMutalist/InfestedMutalist1999Agent": {
    name: "Techrot Skuzzi",
    scans: 20,
  },
  "/Lotus/Types/Enemies/WF1999Infested/InfestedRamSled/InfestedRamSledAgent": {
    name: "Techrot Ramsled",
    scans: 5,
  },
  "/Lotus/Types/Enemies/WF1999Infested/InfestedRunner/InfestedRunner1999Agent": {
    name: "Techrot Galliflex",
    scans: 40,
  },
  "/Lotus/Types/Enemies/WF1999Infested/InfestedUndazoa/InfestedUndazoa1999Agent": {
    name: "Techrot Matmas",
    scans: 20,
  },
  "/Lotus/Types/Enemies/WF1999Infested/InfestedVolatileRunner/InfestedVolatileRunner1999Agent": {
    name: "Techrot Volatile Galliflex",
    scans: 40,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/Disruption/1999DisruptionNox/1999DisruptionNoxAgent": {
    name: "Scaldra Screamer",
    scans: 5,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianButcher/LasrianButcher1999Agent": {
    name: "Scaldra Flayer",
    scans: 20,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianChemStrikeNox/LasrianChemStrikeNox1999Agent": {
    name: "Scaldra Dedicant",
    scans: 5,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianDrone/LasrianDroneAgent": {
    name: "Scaldra Harbinger",
    scans: 20,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianDropship/LasrianSedanAgent": {
    name: "Scaldra TI-92",
    scans: 3,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianGoonadier/LasrianGoonadier1999Agent": {
    name: "Scaldra Eradicator",
    scans: 5,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianRifleLancer/LasrianLancer1999Agent": {
    name: "Scaldra Jaeger",
    scans: 20,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianShieldLancer/LasrianShieldLancer1999Agent": {
    name: "Scaldra Barbican",
    scans: 20,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianTank/LasrianTankAgent": {
    name: "H-09 Efervon Tank",
    scans: 3,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianTank/LasrianTankHardModeAgent": {
    name: "H-09 Apex",
    scans: 3,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianTank/LasrianTankHardModeInfestedAgent": {
    name: "H-09 Apex",
    scans: 3,
  },
  "/Lotus/Types/Enemies/WF1999Lasrian/LasrianTank/LasrianTankInfestedAgent": {
    name: "H-09 Efervon Tank",
    scans: 3,
  },
  "Lotus/Types/Enemies/Corpus/Railjack/CrpCrewMeleeAgent": {
    name: "Taro Stropha Crewman",
    scans: 5,
  },
  "Lotus/Types/Enemies/Grineer/AIWeek/GrineerWorkerB": { name: "Drudge Brazer", scans: 10 },
};
